# -*- coding: utf-8 -*-


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(670, 509)
        MainWindow.setMinimumSize(QtCore.QSize(670, 509))
        MainWindow.setMaximumSize(QtCore.QSize(670, 600))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -20, 671, 741))
        self.label.setMinimumSize(QtCore.QSize(671, 741))
        self.label.setMaximumSize(QtCore.QSize(671, 741))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("icon/pic2.png"))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(50, 50, 311, 101))
        font = QtGui.QFont()
        font.setFamily("华文琥珀")
        font.setPointSize(60)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(320, 20, 261, 151))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.startLogin = QtWidgets.QPushButton(self.centralwidget)
        self.startLogin.setGeometry(QtCore.QRect(190, 210, 311, 71))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(16)
        self.startLogin.setFont(font)
        self.startLogin.setObjectName("startLogin")
        self.Remember = QtWidgets.QCheckBox(self.centralwidget)
        self.Remember.setGeometry(QtCore.QRect(220, 300, 261, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        font.setPointSize(12)
        self.Remember.setFont(font)
        self.Remember.setChecked(False)
        self.Remember.setObjectName("Remember")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(220, 380, 111, 21))
        font = QtGui.QFont()
        font.setFamily("黑体")
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.chooseBrowser = QtWidgets.QComboBox(self.centralwidget)
        self.chooseBrowser.setGeometry(QtCore.QRect(330, 380, 141, 22))
        self.chooseBrowser.setObjectName("chooseBrowser")
        self.chooseBrowser.addItem("")
        self.chooseBrowser.addItem("")
        self.chooseBrowser.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 670, 23))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        self.menu.setObjectName("menu")
        MainWindow.setMenuBar(self.menubar)
        self.help = QtWidgets.QAction(MainWindow)
        self.help.setObjectName("help")
        self.about_Cookie = QtWidgets.QAction(MainWindow)
        self.about_Cookie.setObjectName("about_Cookie")
        self.about = QtWidgets.QAction(MainWindow)
        self.about.setObjectName("about")
        self.menu.addAction(self.help)
        self.menu.addAction(self.about_Cookie)
        self.menu.addSeparator()
        self.menu.addAction(self.about)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Bilibili小空间 by Disy"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:48pt; font-weight:600; color:#ff46af;\">Bilibili</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:36pt; font-weight:600;\">我的小空间</span></p></body></html>"))
        self.startLogin.setText(_translate("MainWindow", "点我开始登录吧！"))
        self.Remember.setText(_translate("MainWindow", "记住我（公共电脑请不要勾选！）"))
        self.label_4.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:12pt;\">登录用浏览器：</span></p></body></html>"))
        self.chooseBrowser.setItemText(0, _translate("MainWindow", "Chrome（谷歌浏览器）"))
        self.chooseBrowser.setItemText(1, _translate("MainWindow", "Edge（微软浏览器）"))
        self.chooseBrowser.setItemText(2, _translate("MainWindow", "Firefox（火狐浏览器）"))
        self.menu.setTitle(_translate("MainWindow", "常见问题"))
        self.help.setText(_translate("MainWindow", "如何使用?"))
        self.about_Cookie.setText(_translate("MainWindow", "(必看!!) Cookie与安全性"))
        self.about.setText(_translate("MainWindow", "关于"))
